### ISSUE TITLE
error with groovy

### ISSUE THREAD

**Issue by maojn** [ssadedin/bpipe#197]
Hi,

I run into the following error while testing bpipe. 

$ echo $PATH
/usr/local/apps/bpipe/0.9.9.2/bin:/usr/local/apps/parpipe/current/scripts:/usr/local/Anaconda/envs/py2.7/bin:/usr/local/bin:/usr/local/mysql/bin:/usr/X11R6/bin:/usr/local/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin:/usr/bin:/usr/X11R6/bin:/home/maoj/bin:/home/maoj/bin
$pwd
/usr/local/apps/bpipe/0.9.9.2/bin
$ ./bpipe run ../helloworld.pipe 
java.lang.ClassNotFoundException: bpipe.Runner
        at org.codehaus.groovy.tools.RootLoader.findClass(RootLoader.java:179)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:151)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:99)
        at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)

Any help is appreciated. Thank you.

**Comment by ssadedin** [comment]
The class it is looking for (bpipe.Runner) should be found in /usr/local/apps/bpipe/0.9.9.2/lib/bpipe.jar - can you check that file exists?

NB: If you just cloned your install out of Github then you need to build first (not if you downloaded the release tar.gz).
