### ISSUE TITLE
Error when running Bpipe

### ISSUE THREAD

**Issue by xuhangliu** [ssadedin/bpipe#204]
Hi,

When I tried to run Bpipe, I got the following error message. Could you help me identify the problem? Thank you! I have JDK version 8 installed on a Ubuntu.
java.lang.ClassNotFoundException: bpipe.Runner
	at org.codehaus.groovy.tools.RootLoader.findClass(RootLoader.java:179)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:99)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)

Xuhang

**Comment by ssadedin** [comment]
Can you say a bit more exactly what you did?

Did you clone the repository and build it? did you download a release (which one?).

The above error might occur if you downloaded the source repository and tried to run it without building. If you can advise some more about what exactly you did then I can provide better feedback.

**Comment by gdevenyi** [comment]
I also had issues with JDK8 with the current release. I just rolled back to JDK7 and it worked.

**Comment by xuhangliu** [comment]
Hi Simon,

I just clone the master repository and place the bin directory in my home path, as instructed here (http://docs.bpipe.org/Overview/InstallInstructions/). How should I build it? Thank you!

Xuhang

**Comment by xuhangliu** [comment]
I tried to download JDK7 from Oracle, but found that it was no longer available there. Do you know where I can download it? @gdevenyi

**Comment by gdevenyi** [comment]
Use the openjdk included in ubuntu, there's no need for Oracle java.

**Comment by drchriscole** [comment]
I've got the same problem. Used the tarball version of 0.9.9.3 and unpacked it. Tried both java 7 & 8 with the same result.
I have bpipe v0.9.8.6 that runs fine.
What's changed between versions?
