### ISSUE TITLE
bpipe/0.9.9.3 "No signature of method: bpipe.executor.CommandTemplate.populateCommandTemplate()..."

### ISSUE THREAD

**Issue by gdevenyi** [ssadedin/bpipe#217]
```
=========================================== Bpipe Error ============================================

An error occurred executing your pipeline:

No signature of method: bpipe.executor.CommandTemplate.populateCommandTemplate() is applicable for argument types: (java.lang.String, java.lang.String, java.util.LinkedHashMap) values: [.bpipe/commandtmp/10, executor/sge-command.template.sh, [max_per_command_threads:16, ...]]
Possible solutions: populateCommandTemplate(java.io.File, java.lang.String, java.util.Map)


Please see the details below for more information.

========================================== Error Details ===========================================

groovy.lang.MissingMethodException: No signature of method: bpipe.executor.CommandTemplate.populateCommandTemplate() is applicable for argument types: (java.lang.String, java.lang.String, java.util.LinkedHashMap) values: [.bpipe/commandtmp/10, executor/sge-command.template.sh, [max_per_command_threads:16, ...]]
Possible solutions: populateCommandTemplate(java.io.File, java.lang.String, java.util.Map)
	at bpipe.executor.SgeCommandExecutor.start(SgeCommandExecutor.groovy:156)
	at bpipe.executor.ThrottledDelegatingCommandExecutor.doStart(ThrottledDelegatingCommandExecutor.groovy:122)
	at bpipe.executor.ThrottledDelegatingCommandExecutor.start(ThrottledDelegatingCommandExecutor.groovy:76)
	at bpipe.CommandManager.start(CommandManager.groovy:149)
	at bpipe.PipelineContext.async(PipelineContext.groovy:1779)
	at bpipe.PipelineContext.async(PipelineContext.groovy)
	at bpipe.PipelineContext.exec(PipelineContext.groovy:1363)
	at bpipe.PipelineContext.exec(PipelineContext.groovy)
	at bpipe.PipelineContext.exec(PipelineContext.groovy:1320)
	at bpipe.PipelineContext.invokeMethod(PipelineContext.groovy)
	at bpipe.PipelineDelegate.methodMissing(PipelineDelegate.groovy:156)
	at bpipe.PipelineDelegate.invokeMethod(PipelineDelegate.groovy)
	at /data/chamal/projects/gabriel/prisma-test/minc-bpipe-library/minc-library.bpipe$_run_closure34.doCall(/data/chamal/projects/gabriel/prisma-test/minc-bpipe-library/minc-library.bpipe.bpipe:532)
	at bpipe.PipelineStage.invokeMethod(PipelineStage.groovy)
	at bpipe.PipelineStage$_runBody_closure3$_closure9.doCall(PipelineStage.groovy:400)
	at bpipe.PipelineStage$_runBody_closure3$_closure9.doCall(PipelineStage.groovy)
	at bpipe.ParamsBinding.withLocalVariables(Runner.groovy:1111)
	at bpipe.PipelineStage$_runBody_closure3.doCall(PipelineStage.groovy:399)
	at bpipe.PipelineStage$_runBody_closure3.doCall(PipelineStage.groovy)
	at bpipe.PipelineStage.runBody(PipelineStage.groovy:387)
	at bpipe.PipelineStage.run(PipelineStage.groovy:248)
	at bpipe.PipelineCategory$_plus_closure3.doCall(PipelineCategory.groovy:151)
	at bpipe.PipelineStage.invokeMethod(PipelineStage.groovy)
	at bpipe.PipelineStage$_runBody_closure3$_closure9.doCall(PipelineStage.groovy:400)
	at bpipe.PipelineStage$_runBody_closure3$_closure9.doCall(PipelineStage.groovy)
	at bpipe.ParamsBinding.withLocalVariables(Runner.groovy:1111)
	at bpipe.PipelineStage$_runBody_closure3.doCall(PipelineStage.groovy:399)
	at bpipe.PipelineStage$_runBody_closure3.doCall(PipelineStage.groovy)
	at bpipe.PipelineStage.runBody(PipelineStage.groovy:387)
	at bpipe.PipelineStage.run(PipelineStage.groovy:248)
	at bpipe.PipelineCategory$_plus_closure3.doCall(PipelineCategory.groovy:151)
	at bpipe.PipelineStage.invokeMethod(PipelineStage.groovy)
	at bpipe.PipelineStage$_runBody_closure3$_closure9.doCall(PipelineStage.groovy:400)
	at bpipe.PipelineStage$_runBody_closure3$_closure9.doCall(PipelineStage.groovy)
	at bpipe.ParamsBinding.withLocalVariables(Runner.groovy:1111)
	at bpipe.PipelineStage$_runBody_closure3.doCall(PipelineStage.groovy:399)
	at bpipe.PipelineStage$_runBody_closure3.doCall(PipelineStage.groovy)
	at bpipe.PipelineStage.runBody(PipelineStage.groovy:387)
	at bpipe.PipelineStage.run(PipelineStage.groovy:248)
	at bpipe.PipelineCategory$_plus_closure3.doCall(PipelineCategory.groovy:151)
	at bpipe.PipelineStage.invokeMethod(PipelineStage.groovy)
	at bpipe.PipelineStage$_runBody_closure3$_closure9.doCall(PipelineStage.groovy:400)
	at bpipe.PipelineStage$_runBody_closure3$_closure9.doCall(PipelineStage.groovy)
	at bpipe.ParamsBinding.withLocalVariables(Runner.groovy:1111)
	at bpipe.PipelineStage$_runBody_closure3.doCall(PipelineStage.groovy:399)
	at bpipe.PipelineStage$_runBody_closure3.doCall(PipelineStage.groovy)
	at bpipe.PipelineStage.runBody(PipelineStage.groovy:387)
	at bpipe.PipelineStage.run(PipelineStage.groovy:248)
	at bpipe.PipelineCategory$_plus_closure3.doCall(PipelineCategory.groovy:151)
	at bpipe.PipelineStage.invokeMethod(PipelineStage.groovy)
	at bpipe.PipelineStage$_runBody_closure3$_closure9.doCall(PipelineStage.groovy:400)
	at bpipe.PipelineStage$_runBody_closure3$_closure9.doCall(PipelineStage.groovy)
	at bpipe.ParamsBinding.withLocalVariables(Runner.groovy:1111)
	at bpipe.PipelineStage$_runBody_closure3.doCall(PipelineStage.groovy:399)
	at bpipe.PipelineStage$_runBody_closure3.doCall(PipelineStage.groovy)
	at bpipe.PipelineStage.runBody(PipelineStage.groovy:387)
	at bpipe.PipelineStage.run(PipelineStage.groovy:248)
	at bpipe.PipelineCategory$_plus_closure3.doCall(PipelineCategory.groovy:151)
	at bpipe.PipelineStage.invokeMethod(PipelineStage.groovy)
	at bpipe.PipelineStage$_runBody_closure3$_closure9.doCall(PipelineStage.groovy:400)
	at bpipe.PipelineStage$_runBody_closure3$_closure9.doCall(PipelineStage.groovy)
	at bpipe.ParamsBinding.withLocalVariables(Runner.groovy:1111)
	at bpipe.PipelineStage$_runBody_closure3.doCall(PipelineStage.groovy:399)
	at bpipe.PipelineStage$_runBody_closure3.doCall(PipelineStage.groovy)
	at bpipe.PipelineStage.runBody(PipelineStage.groovy:387)
	at bpipe.PipelineStage.run(PipelineStage.groovy:248)
	at bpipe.Pipeline.runSegment(Pipeline.groovy:546)
	at bpipe.Pipeline$runSegment$9.call(Unknown Source)
	at bpipe.PipelineCategory$_splitOnMap_closure12$_closure40.doCall(PipelineCategory.groovy:545)
	at bpipe.PipelineCategory$_splitOnMap_closure12$_closure40.doCall(PipelineCategory.groovy)
```

**Comment by gdevenyi** [comment]
Using openjdk-8

**Comment by ssadedin** [comment]
Hopefully fixed with above commit - let me know if you still encounter issues.

Thanks for reporting the problem!

**Comment by gdevenyi** [comment]
Seems to be fixed. Thanks.

**Comment by JerryDing** [comment]
More details?
