### ISSUE TITLE
bpipe "java.lang.ClassNotFoundException: bpipe.Runner"

### ISSUE THREAD

**Issue by jsolvason** [ssadedin/bpipe#221]
Hi,

I am trying to run the [PARpipe](https://github.com/ohlerlab/PARpipe) pipeline. It is dependent on bpipe. I run into the same error no matter how bpipe is called (whether within PARpipe, trying the helloworld.pipe or simply calling bpipe without arguments or options).

```
java.lang.ClassNotFoundException: bpipe.Runner
    at org.codehaus.groovy.tools.RootLoader.findClass(RootLoader.java:179)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:151)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:99)
    at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)
```

Ive found a couple of previous issues [here](https://github.com/ssadedin/bpipe/issues/197) and [here](https://github.com/ssadedin/bpipe/issues/71), but nothing has worked. Also, it seems like when you answer sometimes issue-raiser does not respond...

I tried both downloading and cloning the repository. The bpipe bin directory is in my PATH variable (see below). 

`/home/chimera/bpipe/bin`

Any ideas? Any other information I could provide you with? Any help would be... well helpful.

My versions:
Java 1.8.0_131 
Ubuntu 16.04.2 LTS

Best

Joe

**Comment by ssadedin** [comment]
I think the problem is that this issue is a general side effect any time the path Bpipe computes for its own install directory is incorrect. So although the symptom is common, the cause is often not the same in each case. You can see the logic being used here:

https://github.com/ssadedin/bpipe/blob/master/bin/bpipe#L361

Could you check out the steps in there and see if you can figure out where it goes wrong in your case? To help debug, you could also do the following:

```bash
export SHOWDEBUG=true
```

Then run the pipeline as normal - it should print out a bunch of stuff showing how it tries to run the actual java command that starts Bpipe. If you can paste that back here we might be able to figure out what is wrong.

**Comment by jsolvason** [comment]
Not sure how useful I'll be at looking inside the installation code but I'll give it a go. For now here's my verbose output. I assume calling bpipe alone is enough to get what you're looking for to debug? 

#export SHOWDEBUG=true

```
chimera@chimera-parclip:~$ bpipe
DEBUG: classpath=/home/chimera/bpipe/bin/../local-lib/*:/home/chimera/bpipes/extra-lib.jar
JAVA_MEM: 
LAUNCH_CMD: 
   printf $$ > .bpipe.2286.run.pid &
   exec java -Xmx256m \
             -noverify \
             -classpath "/home/chimera/bpipe/bin/../local-lib/*:/home/chimera/bpipes/extra-lib.jar"   \
             -Dbpipe.pid=2286 \
             -Dbpipe.home=/home/chimera/bpipe/bin/.. \
             -Dbpipe.version=0.0.0 \
             -Dbpipe.builddate=0 \
                 org.codehaus.groovy.tools.GroovyStarter \
                    --classpath "/home/chimera/bpipe/bin/../local-lib/*:/home/chimera/bpipes/extra-lib.jar" \
                    --main bpipe.Runner   > .bpipe/logs/$$.log 2>&1

DEBUG:  Launched Java with PID 2297
java.lang.ClassNotFoundException: bpipe.Runner
    at org.codehaus.groovy.tools.RootLoader.findClass(RootLoader.java:179)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:151)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:99)
    at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)
```

**Comment by ssadedin** [comment]
Oh, maybe it's simpler than I thought: did you download the source distribution instead of the binary? I think that is the reason the version would be showing up as 0.0.0.

If you got the source you can build it first with:

```
./gradlew
```

Can you check that and see if that's the reason?

**Comment by jsolvason** [comment]
Looks like the build was successful but still getting the same error (copy-pasted below in case it is slightly different than before). Still looks like version = 0.0.0.

If you were to install bpipe right now, what exactly would you do? I did the following:

1. Clone from github 
`$ git clone https://github.com/ssadedin/bpipe.git`

2. Navigate into bpipe directory
`$ cd bpipe`
```
$ ./gradlew
================================================================================
      No Gridgain library found. Gridgain support disabled in this build.       
================================================================================

:help

Welcome to Gradle 2.0.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

BUILD SUCCESSFUL

Total time: 6.072 secs
```

3. Try bpipe
```
$ bpipe
DEBUG: classpath=/home/chimera/bpipe/bin/../local-lib/*:/home/chimera/bpipes/extra-lib.jar
JAVA_MEM: 
LAUNCH_CMD: 
   printf $$ > .bpipe.2314.run.pid &
   exec java -Xmx256m \
             -noverify \
             -classpath "/home/chimera/bpipe/bin/../local-lib/*:/home/chimera/bpipes/extra-lib.jar"   \
             -Dbpipe.pid=2314 \
             -Dbpipe.home=/home/chimera/bpipe/bin/.. \
             -Dbpipe.version=0.0.0 \
             -Dbpipe.builddate=0 \
                 org.codehaus.groovy.tools.GroovyStarter \
                    --classpath "/home/chimera/bpipe/bin/../local-lib/*:/home/chimera/bpipes/extra-lib.jar" \
                    --main bpipe.Runner   > .bpipe/logs/$$.log 2>&1

DEBUG:  Launched Java with PID 2326
java.lang.ClassNotFoundException: bpipe.Runner
    at org.codehaus.groovy.tools.RootLoader.findClass(RootLoader.java:179)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:151)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:99)
    at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)
```

**Comment by ssadedin** [comment]
I'm sorry, try this instead:

./gradlew clean jar

**Comment by jsolvason** [comment]
That worked!

I also had to explicitly install a java JDK (preloaded java didn't work).
https://www3.ntu.edu.sg/home/ehchua/programming/howto/JDK_Howto.html

Was this something I should have known how to do (./gradlew clean jar), or
did I miss it in the docs somewhere? I could only find one link to download
bpipe on github. Not sure where to access the binary files.

Thanks!

Joe


Joseph Solvason
Chimera Bioengineering

**Comment by jsolvason** [comment]
Weird though... Still says the version is 0.0.0 and build on Wed Dec 31
16:00:00 PST 1969


Joseph Solvason
Chimera Bioengineering

**Comment by ssadedin** [comment]
You shouldn't need JDK etc normally because you should be getting the binary download.

I browsed around a bit to find the link that mislead you but couldn't locate it. There should be a link to the binary directly on the releases page:  https://github.com/ssadedin/bpipe/releases.

**Comment by jsolvason** [comment]
I just cloned it using the link below. Should this have downloaded the binary file? 

`$ git clone https://github.com/ssadedin/bpipe.git`

I'm more or less still getting into bioinformatics. As a rule of thumb, would you suggest downloading programs from the github.com/user/program/releases subdirectory?
