### ISSUE TITLE
Install fails.

### ISSUE THREAD

**Issue by drtconway** [ssadedin/bpipe#267]
Hi Bpipies,

I'm trying to do a clean install of bpipe on ubuntu (Groovy - that's the release, not the language) and it fails:

```
$ docker run -it ubuntu:groovy bash
# apt update && apt install -y git openjdk-15-jre-headless
...
# cd /opt
# git clone https://github.com/ssadedin/bpipe.git
...
# export PATH=/opt/bpipe/bin:${PATH}
# bipe
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Error: Could not find or load main class org.codehaus.groovy.tools.GroovyStarter
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.tools.GroovyStarter
```

It appears the groovy jar got dropped from the class path.

I hacked in a fix to test it:
```
$ git diff
diff --git a/bin/bpipe b/bin/bpipe
index cc4dbea7..385808b1 100755
--- a/bin/bpipe
+++ b/bin/bpipe
@@ -262,7 +262,7 @@ get_classpath() {
         BPIPE_JAR="$BPIPE_HOME/eclipse-build:$BPIPE_HOME/build/libs/bpipe.jar"
   fi
 
-  CP="$BPIPE_HOME"/$LIB/*:$HOME/bpipes/extra-lib.jar:"$BPIPE_HOME"/lib/bpipe-cloud.jar:
+  CP="$BPIPE_HOME"/$LIB/*:$HOME/bpipes/extra-lib.jar:"$BPIPE_HOME"/lib/bpipe-cloud.jar:"$BPIPE_HOME"/groovy-lib/*
 
   # In case we are running in place in the bpipe project root, we pre-empt any other 
   # bpipe classes with those from the build directory and the eclipse compile path
```

Now I get a different error:

```
# OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
java.lang.ClassNotFoundException: bpipe.Runner9
	at org.codehaus.groovy.tools.RootLoader.findClass(RootLoader.java:177)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:149)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:104)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:128)
```

A grep finds no instances of Runner9 in the source tree. Am I missing something?

**Comment by drtconway** [comment]
Looks like a java version problem. Downgraded to 8. Will update with progress.

**Comment by drtconway** [comment]
Looks like a user error: replace user and press any key.
