### ISSUE TITLE
GroovyStarter error

### ISSUE THREAD

**Issue by lonsbio** [ssadedin/bpipe#71]
_From [cboust...@gmail.com](https://code.google.com/u/116548269372547513801/) on 2013-02-23T02:45:23Z_

What steps will reproduce the problem? 1. Download and unzip bpipe
2. Tried to run helloworld.pipe example from documentation (bpipe run helloworld.pipe)
3. get the error below What is the expected output? What do you see instead? Exception in thread "main" java.lang.NoClassDefFoundError: org/codehaus/groovy/tools/GroovyStarter
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.tools.GroovyStarter
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: org.codehaus.groovy.tools.GroovyStarter. Program will exit. What version of the product are you using? On what operating system? bpipe-0.9.7.tar.gz
Ubuntu 12.04 LTS Please provide any additional information below. Downloaded bpipe, tried to run the helloworld.pipe example.

Complained about Groovey not being present

Installed groovey

put GROOVEY_HOME and JAVA_HOME on path (ensuring to use java 1.6)

Still got the error

_Original issue: http://code.google.com/p/bpipe/issues/detail?id=71_

**Comment by jsolvason** [comment]
I am getting same error... Has this been resolved somewhere else?
