### ISSUE TITLE
SGE - problem specifying parallel environment

### ISSUE THREAD

**Issue by lonsbio** [ssadedin/bpipe#96]
_From [mphoepp...@gmail.com](https://code.google.com/u/116481381496220708790/) on 2014-04-15T18:25:20Z_

Hi,

switched our cluster to SGE the other day and wanted to run a simple bpipe pipeline. However, specifying resources as described in the documentation yields an error. For example, we have a PE called 'nodejob', so I specify:

procs="nodejob 8"

When running this, I get

An error occurred executing your pipeline:

```
                               For input string: "nodejob 8"                                    
```

Please see the details below for more information.

========================================== Error Details ===========================================

java.lang.NumberFormatException: For input string: "nodejob 8"
        at bpipe.PipelineContext.async(PipelineContext.groovy:1468)
        at bpipe.PipelineContext.async(PipelineContext.groovy)
        at bpipe.PipelineContext.exec(PipelineContext.groovy:1272)
        at bpipe.PipelineContext.exec(PipelineContext.groovy:1221)
        at bpipe.PipelineContext.invokeMethod(PipelineContext.groovy)
        at bpipe.PipelineDelegate.methodMissing(PipelineDelegate.groovy:133)
        at bpipe.PipelineDelegate.invokeMethod(PipelineDelegate.groovy)
        at Script1$_run_closure2_closure8.doCall(Script1.groovy:35)
        at Script1$_run_closure2_closure8.doCall(Script1.groovy)
[SNIP]

Bpipe version: 0.9.8.6_beta_3
Grid engine version: OGS/GE 2011.11

_Original issue: http://code.google.com/p/bpipe/issues/detail?id=96_

**Comment by gdevenyi** [comment]
Solved be new template system, can be closed.
